# Production docker-compose with external Traefik
services:
  json-formatter:
    build: .
    container_name: json-formatter
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.json-formatter.rule=Host(`json.hobbycodes.com`) || Host(`hobbycodes.com`)
      - traefik.http.routers.json-formatter.entrypoints=websecure
      - traefik.http.routers.json-formatter.tls.certresolver=letsencrypt
      - traefik.http.routers.json-formatter.middlewares=gzip-compression@file
      - traefik.http.services.json-formatter.loadbalancer.server.port=80
    networks:
      - web
    healthcheck:
      test: ['CMD', 'wget', '--quiet', '--tries=1', '--spider', 'http://localhost/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  web:
    external: true
